-- MySQL Script generated by MySQL Workbench
-- Sun Dec  8 17:55:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema eeroju_news
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eeroju_news
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eeroju_news` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `eeroju_news` ;

-- -----------------------------------------------------
-- Table `eeroju_news`.`user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eeroju_news`.`user_info` (
  `id` BINARY(16) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `fcm_registration_key` VARCHAR(255) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `mobile_number` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `profile_image_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `eeroju_news`.`country_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eeroju_news`.`country_info` (
  `id` BINARY(16) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `country_name` VARCHAR(255) NOT NULL,
  `user_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKqjk6ds2wgej1j0jwg6n6y3let` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKqjk6ds2wgej1j0jwg6n6y3let`
    FOREIGN KEY (`user_id`)
    REFERENCES `eeroju_news`.`user_info` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `eeroju_news`.`state_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eeroju_news`.`state_info` (
  `id` BINARY(16) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `state_name` VARCHAR(255) NOT NULL,
  `country_id` BINARY(16) NOT NULL,
  `user_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKmw4salkyrpeq8nm7jx9ws6jj4` (`country_id` ASC) VISIBLE,
  INDEX `FKhbv7ase0qc5iwlbftt8bav665` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKhbv7ase0qc5iwlbftt8bav665`
    FOREIGN KEY (`user_id`)
    REFERENCES `eeroju_news`.`user_info` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FKmw4salkyrpeq8nm7jx9ws6jj4`
    FOREIGN KEY (`country_id`)
    REFERENCES `eeroju_news`.`country_info` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `eeroju_news`.`district_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eeroju_news`.`district_info` (
  `id` BINARY(16) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `district_name` VARCHAR(255) NOT NULL,
  `country_id` BINARY(16) NOT NULL,
  `state_id` BINARY(16) NOT NULL,
  `user_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKt8f76wyjx7abnudst0p102a1t` (`country_id` ASC) VISIBLE,
  INDEX `FKchqcdj433t4an50mcdrg12cp1` (`state_id` ASC) VISIBLE,
  INDEX `FK6k217d45vmqotmf84rpguymdi` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK6k217d45vmqotmf84rpguymdi`
    FOREIGN KEY (`user_id`)
    REFERENCES `eeroju_news`.`user_info` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FKchqcdj433t4an50mcdrg12cp1`
    FOREIGN KEY (`state_id`)
    REFERENCES `eeroju_news`.`state_info` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FKt8f76wyjx7abnudst0p102a1t`
    FOREIGN KEY (`country_id`)
    REFERENCES `eeroju_news`.`country_info` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `eeroju_news`.`area_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eeroju_news`.`area_info` (
  `id` BINARY(16) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `area_name` VARCHAR(255) NOT NULL,
  `country_id` BINARY(16) NOT NULL,
  `district_id` BINARY(16) NOT NULL,
  `state_id` BINARY(16) NOT NULL,
  `user_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKi7ucu85anlura9emtn91a38kh` (`country_id` ASC) VISIBLE,
  INDEX `FKoq9qhhr5ddat0dok2yiqk6e0p` (`district_id` ASC) VISIBLE,
  INDEX `FKl48fodfjdcvtoqku877fpxpeq` (`state_id` ASC) VISIBLE,
  INDEX `FKnajb3mu4lx02c51mio15jenes` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKi7ucu85anlura9emtn91a38kh`
    FOREIGN KEY (`country_id`)
    REFERENCES `eeroju_news`.`country_info` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FKl48fodfjdcvtoqku877fpxpeq`
    FOREIGN KEY (`state_id`)
    REFERENCES `eeroju_news`.`state_info` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FKnajb3mu4lx02c51mio15jenes`
    FOREIGN KEY (`user_id`)
    REFERENCES `eeroju_news`.`user_info` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FKoq9qhhr5ddat0dok2yiqk6e0p`
    FOREIGN KEY (`district_id`)
    REFERENCES `eeroju_news`.`district_info` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `eeroju_news`.`content_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eeroju_news`.`content_info` (
  `id` BINARY(16) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `content_length` BIGINT(20) NOT NULL,
  `content_type` VARCHAR(255) NOT NULL,
  `file_extension` VARCHAR(255) NOT NULL,
  `file_name` VARCHAR(255) NOT NULL,
  `file_path` VARCHAR(255) NOT NULL,
  `is_encrypted` TINYINT(4) NOT NULL,
  `md5_check_sum` VARCHAR(255) NOT NULL,
  `meta_data` JSON NULL DEFAULT NULL,
  `service_id` VARCHAR(255) NOT NULL,
  `tenant_id` VARCHAR(255) NOT NULL,
  `user_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `eeroju_news`.`news_item_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eeroju_news`.`news_item_info` (
  `id` BINARY(16) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `content_type` VARCHAR(255) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `head_line` VARCHAR(255) NOT NULL,
  `image_url` VARCHAR(255) NOT NULL,
  `news_type` VARCHAR(255) NOT NULL,
  `user_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK9nd8o2kveogjbawjdjj9c0pm5` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK9nd8o2kveogjbawjdjj9c0pm5`
    FOREIGN KEY (`user_id`)
    REFERENCES `eeroju_news`.`user_info` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `eeroju_news`.`news_item_location_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eeroju_news`.`news_item_location_info` (
  `id` BINARY(16) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `is_international` BIT(1) NULL DEFAULT NULL,
  `area_id` BINARY(16) NOT NULL,
  `country_id` BINARY(16) NOT NULL,
  `district_id` BINARY(16) NOT NULL,
  `news_item_info_id` BINARY(16) NOT NULL,
  `state_id` BINARY(16) NOT NULL,
  `user_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_9557nwphypptd8g2j4strluds` (`news_item_info_id` ASC) VISIBLE,
  INDEX `FKf9trc1ox00px3tasopxg6d56e` (`area_id` ASC) VISIBLE,
  INDEX `FKgjhw3igpcur4sm8qwf2i5gtau` (`country_id` ASC) VISIBLE,
  INDEX `FK2t7x1trglp55x71b4t9erji3j` (`district_id` ASC) VISIBLE,
  INDEX `FKtmi0iw512jp77ninxvli97bff` (`state_id` ASC) VISIBLE,
  INDEX `FKc1i282gln2yvti6b4s3eeoeis` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK2t7x1trglp55x71b4t9erji3j`
    FOREIGN KEY (`district_id`)
    REFERENCES `eeroju_news`.`district_info` (`id`),
  CONSTRAINT `FK77i45tdl8fvbacttwih0bbx51`
    FOREIGN KEY (`news_item_info_id`)
    REFERENCES `eeroju_news`.`news_item_info` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FKc1i282gln2yvti6b4s3eeoeis`
    FOREIGN KEY (`user_id`)
    REFERENCES `eeroju_news`.`user_info` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FKf9trc1ox00px3tasopxg6d56e`
    FOREIGN KEY (`area_id`)
    REFERENCES `eeroju_news`.`area_info` (`id`),
  CONSTRAINT `FKgjhw3igpcur4sm8qwf2i5gtau`
    FOREIGN KEY (`country_id`)
    REFERENCES `eeroju_news`.`country_info` (`id`),
  CONSTRAINT `FKtmi0iw512jp77ninxvli97bff`
    FOREIGN KEY (`state_id`)
    REFERENCES `eeroju_news`.`state_info` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `eeroju_news`.`news_item_social_shares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eeroju_news`.`news_item_social_shares` (
  `id` BINARY(16) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `facebook_shares` INT(11) NULL DEFAULT NULL,
  `hello_app_shares` INT(11) NULL DEFAULT NULL,
  `instagram_shares` INT(11) NULL DEFAULT NULL,
  `telegram_shares` INT(11) NULL DEFAULT NULL,
  `twitter_shares` INT(11) NULL DEFAULT NULL,
  `views` INT(11) NULL DEFAULT NULL,
  `whats_app_shares` INT(11) NULL DEFAULT NULL,
  `news_item_info_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_ixg121xp6jphtmjrfjujq9493` (`news_item_info_id` ASC) VISIBLE,
  CONSTRAINT `FK946hx5b3d27ifx8hef9ncuiqe`
    FOREIGN KEY (`news_item_info_id`)
    REFERENCES `eeroju_news`.`news_item_info` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `eeroju_news`.`news_item_user_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eeroju_news`.`news_item_user_comments` (
  `id` BINARY(16) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `comment` VARCHAR(255) NOT NULL,
  `news_item_info_id` BINARY(16) NOT NULL,
  `user_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKfeu7gnodntotbccqpkgfgimyh` (`news_item_info_id` ASC) VISIBLE,
  INDEX `FKfw4t3cwnot0nkieu05np0vdfv` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKfeu7gnodntotbccqpkgfgimyh`
    FOREIGN KEY (`news_item_info_id`)
    REFERENCES `eeroju_news`.`news_item_info` (`id`),
  CONSTRAINT `FKfw4t3cwnot0nkieu05np0vdfv`
    FOREIGN KEY (`user_id`)
    REFERENCES `eeroju_news`.`user_info` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `eeroju_news`.`news_item_user_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eeroju_news`.`news_item_user_likes` (
  `id` BINARY(16) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `news_item_info_id` BINARY(16) NOT NULL,
  `user_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKqa8g5mchsfm5udghk1d069yb4` (`news_item_info_id` ASC) VISIBLE,
  INDEX `FKn9sk60h657f8msgh9u64o0l3` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKn9sk60h657f8msgh9u64o0l3`
    FOREIGN KEY (`user_id`)
    REFERENCES `eeroju_news`.`user_info` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FKqa8g5mchsfm5udghk1d069yb4`
    FOREIGN KEY (`news_item_info_id`)
    REFERENCES `eeroju_news`.`news_item_info` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `eeroju_news`.`news_item_user_un_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eeroju_news`.`news_item_user_un_likes` (
  `id` BINARY(16) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `news_item_info_id` BINARY(16) NOT NULL,
  `user_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKoou6qp9286w7ni1akl614n08r` (`news_item_info_id` ASC) VISIBLE,
  INDEX `FKg660b7ju430m6ghf4oyqmrfl` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKg660b7ju430m6ghf4oyqmrfl`
    FOREIGN KEY (`user_id`)
    REFERENCES `eeroju_news`.`user_info` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FKoou6qp9286w7ni1akl614n08r`
    FOREIGN KEY (`news_item_info_id`)
    REFERENCES `eeroju_news`.`news_item_info` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `eeroju_news`.`news_item_video_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eeroju_news`.`news_item_video_info` (
  `id` BINARY(16) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `duration` VARCHAR(255) NULL DEFAULT NULL,
  `size` VARCHAR(255) NULL DEFAULT NULL,
  `thumbnail_image_url` VARCHAR(255) NOT NULL,
  `video_type` VARCHAR(255) NOT NULL,
  `video_url` VARCHAR(255) NULL DEFAULT NULL,
  `youtube_video_id` VARCHAR(255) NULL DEFAULT NULL,
  `news_item_info_id` BINARY(16) NOT NULL,
  `user_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_rxba31rtpehvri9w8lwdyicdl` (`news_item_info_id` ASC) VISIBLE,
  INDEX `FKoy6gpbhlmsocwwb2p11a9n7x0` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKegmvul04dr4n5kv3whmx7ffl8`
    FOREIGN KEY (`news_item_info_id`)
    REFERENCES `eeroju_news`.`news_item_info` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FKoy6gpbhlmsocwwb2p11a9n7x0`
    FOREIGN KEY (`user_id`)
    REFERENCES `eeroju_news`.`user_info` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `eeroju_news`.`poll_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eeroju_news`.`poll_info` (
  `id` BINARY(16) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `correct_option_number` INT(11) NOT NULL,
  `poll_type` VARCHAR(255) NOT NULL,
  `question` VARCHAR(255) NOT NULL,
  `user_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK95rbex875w27yrhtobb52xstu` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK95rbex875w27yrhtobb52xstu`
    FOREIGN KEY (`user_id`)
    REFERENCES `eeroju_news`.`user_info` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `eeroju_news`.`poll_options_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eeroju_news`.`poll_options_info` (
  `id` BINARY(16) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `option_name` VARCHAR(255) NOT NULL,
  `option_number` INT(11) NOT NULL,
  `poll_id` BINARY(16) NOT NULL,
  `user_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKh7b4nwjx291j9fylp28l76i3g` (`poll_id` ASC) VISIBLE,
  INDEX `FKplj0agxgj1omhhbghm3dmu0sv` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKh7b4nwjx291j9fylp28l76i3g`
    FOREIGN KEY (`poll_id`)
    REFERENCES `eeroju_news`.`poll_info` (`id`),
  CONSTRAINT `FKplj0agxgj1omhhbghm3dmu0sv`
    FOREIGN KEY (`user_id`)
    REFERENCES `eeroju_news`.`user_info` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `eeroju_news`.`poll_transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eeroju_news`.`poll_transactions` (
  `id` BINARY(16) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `option_data` VARCHAR(255) NULL DEFAULT NULL,
  `poll_id` BINARY(16) NOT NULL,
  `poll_option_info_id` BINARY(16) NOT NULL,
  `user_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKnt1sgsqbot9wmct5pq8ptwtnv` (`poll_id` ASC) VISIBLE,
  INDEX `FKf0y81h4sdv7qie3i796tdwwql` (`poll_option_info_id` ASC) VISIBLE,
  INDEX `FKbxexlr2o9uuq74vp3jhjtcegm` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKbxexlr2o9uuq74vp3jhjtcegm`
    FOREIGN KEY (`user_id`)
    REFERENCES `eeroju_news`.`user_info` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FKf0y81h4sdv7qie3i796tdwwql`
    FOREIGN KEY (`poll_option_info_id`)
    REFERENCES `eeroju_news`.`poll_options_info` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FKnt1sgsqbot9wmct5pq8ptwtnv`
    FOREIGN KEY (`poll_id`)
    REFERENCES `eeroju_news`.`poll_info` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `eeroju_news`.`user_profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eeroju_news`.`user_profiles` (
  `id` BINARY(16) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `gender` VARCHAR(10) NULL DEFAULT NULL,
  `area_id` BINARY(16) NOT NULL,
  `country_id` BINARY(16) NOT NULL,
  `district_id` BINARY(16) NOT NULL,
  `state_id` BINARY(16) NOT NULL,
  `user_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_e5h89rk3ijvdmaiig4srogdc6` (`user_id` ASC) VISIBLE,
  INDEX `FKlhv8oay0js429il1kn67lcejm` (`area_id` ASC) VISIBLE,
  INDEX `FKb64mtuv9p6kw0j69xpikmbpcp` (`country_id` ASC) VISIBLE,
  INDEX `FKfv3lui16n44yqnj1w4pa9xllb` (`district_id` ASC) VISIBLE,
  INDEX `FK9wipwgi5br15ncb0jyb7siyu6` (`state_id` ASC) VISIBLE,
  CONSTRAINT `FK9wipwgi5br15ncb0jyb7siyu6`
    FOREIGN KEY (`state_id`)
    REFERENCES `eeroju_news`.`state_info` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FKb64mtuv9p6kw0j69xpikmbpcp`
    FOREIGN KEY (`country_id`)
    REFERENCES `eeroju_news`.`country_info` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FKfv3lui16n44yqnj1w4pa9xllb`
    FOREIGN KEY (`district_id`)
    REFERENCES `eeroju_news`.`district_info` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FKjqcy60kmh43ju6ljm5j1na2jk`
    FOREIGN KEY (`user_id`)
    REFERENCES `eeroju_news`.`user_info` (`id`),
  CONSTRAINT `FKlhv8oay0js429il1kn67lcejm`
    FOREIGN KEY (`area_id`)
    REFERENCES `eeroju_news`.`area_info` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
