# Http-Method
POST

# API URL : /v1/api/locations/{userId}/states
http://localhost:9191/v1/api/locations/244d5bdf-904c-43f1-9781-c5d8b19821ed/states

# Http Request Headers
@Content-Type: application/json

# Request Body

{
  "stateNames": [
    "Andhra Pradesh",
    "Telangana"
  ],
  "countryId": "7001f768-a24d-4654-aa18-d0de157e7457"
}

%%%

# Duration: 243 ms
# URL: http://localhost:9191/v1/api/locations/244d5bdf-904c-43f1-9781-c5d8b19821ed/states

# HTTP/1.1 200

@Vary: Origin
@Vary: Access-Control-Request-Method
@Vary: Access-Control-Request-Headers
@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Fri, 13 Dec 2019 17:46:50 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive

{
  "success": true,
  "message": "Created Successfully"
}