# Http-Method
GET

# API URL : /v1/api/locations/{userId}/areas/{districtId}
http://localhost:9191/v1/api/locations/244d5bdf-904c-43f1-9781-c5d8b19821ed/areas/c86b11e8-1a59-4c3c-8d06-4d5f36f1a464

%%%

# Duration: 62 ms
# URL: http://localhost:9191/v1/api/locations/244d5bdf-904c-43f1-9781-c5d8b19821ed/areas/c86b11e8-1a59-4c3c-8d06-4d5f36f1a464

# HTTP/1.1 200

@Vary: Origin
@Vary: Access-Control-Request-Method
@Vary: Access-Control-Request-Headers
@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Fri, 13 Dec 2019 18:00:21 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive

[
  {
    "createdAt": "2019-12-13 23:28:54",
    "updatedAt": "2019-12-13 23:28:54",
    "id": "58178bd3-dc38-4a3b-b12e-659acc1adbee",
    "areaName": "Narsipatnam"
  },
  {
    "createdAt": "2019-12-13 23:28:54",
    "updatedAt": "2019-12-13 23:28:54",
    "id": "7db2bab2-70ec-413b-b7fb-fcf0c91376dc",
    "areaName": "Visakhapatnam"
  },
  {
    "createdAt": "2019-12-13 23:28:54",
    "updatedAt": "2019-12-13 23:28:54",
    "id": "a83fe867-360d-4e93-a14b-528d2a9eab46",
    "areaName": "Anakapalli"
  }
]