# Http-Method
GET

# API URL : /v1/api/locations/{userId}/states/{countryId}
http://localhost:9191/v1/api/locations/244d5bdf-904c-43f1-9781-c5d8b19821ed/states/7001f768-a24d-4654-aa18-d0de157e7457

%%%

# Duration: 85 ms
# URL: http://localhost:9191/v1/api/locations/244d5bdf-904c-43f1-9781-c5d8b19821ed/states/7001f768-a24d-4654-aa18-d0de157e7457

# HTTP/1.1 200

@Vary: Origin
@Vary: Access-Control-Request-Method
@Vary: Access-Control-Request-Headers
@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Fri, 13 Dec 2019 17:48:22 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive

[
  {
    "createdAt": "2019-12-13 23:16:50",
    "updatedAt": "2019-12-13 23:16:50",
    "id": "32f7beaf-8382-440e-9f0f-d2cee8ee83f4",
    "stateName": "Telangana"
  },
  {
    "createdAt": "2019-12-13 23:16:50",
    "updatedAt": "2019-12-13 23:16:50",
    "id": "cea1445a-7fbf-4ba5-9a64-5b7b18de63a4",
    "stateName": "Andhra Pradesh"
  }
]