# Http-Method
POST

# API URL : /v1/api/news/{userId}/{newsItemId}/action
http://localhost:9191/v1/api/news/244d5bdf-904c-43f1-9781-c5d8b19821ed/69a76cd8-ab31-4a7f-a83c-438804c45b64/action
&actionType=LIKE


%%%

# Duration: 303 ms
# URL: http://localhost:9191/v1/api/news/244d5bdf-904c-43f1-9781-c5d8b19821ed/69a76cd8-ab31-4a7f-a83c-438804c45b64/action?&actionType=LIKE

# HTTP/1.1 200

@Vary: Origin
@Vary: Access-Control-Request-Method
@Vary: Access-Control-Request-Headers
@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Sat, 14 Dec 2019 07:43:37 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive

{
  "views": 2,
  "likes": 1,
  "unLikes": 0,
  "comments": 0,
  "whatsAppShares": 0,
  "facebookShares": 1,
  "instagramShares": 0,
  "helloAppShares": 0,
  "twitterShares": 0,
  "telegramShares": 0,
  "newsItemId": "69a76cd8-ab31-4a7f-a83c-438804c45b64"
}