# Http-Method
POST

# API URL : /v1/api/news/{userId}/{newsItemId}/action
http://localhost:9191/v1/api/news/1/11/action
&actionType=LIKE


%%%

# Duration: 587 ms
# URL: http://localhost:9191/v1/api/news/1/11/action?&actionType=LIKE

# HTTP/1.1 200

@Vary: Origin
@Vary: Access-Control-Request-Method
@Vary: Access-Control-Request-Headers
@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Wed, 18 Dec 2019 17:11:44 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive

{
  "views": 0,
  "likes": 1,
  "unLikes": 0,
  "comments": 0,
  "whatsAppShares": 0,
  "facebookShares": 0,
  "instagramShares": 0,
  "helloAppShares": 0,
  "twitterShares": 0,
  "telegramShares": 0,
  "newsItemId": 11
}