# Http-Method
POST

# API URL : /v1/api/polls/{userId}
http://localhost:9191/v1/api/polls/244d5bdf-904c-43f1-9781-c5d8b19821ed

# Http Request Headers
@Content-Type: application/json

# Request Body

{
  "question": "When would you purchase a DVD player if you have already own one?",
  "choices": [
    {
      "text": "In the next 6 months"
    },
    {
      "text": "Within 1 year"
    },
    {
      "text": "Within 2 years"
    },
    {
      "text": "Already own a DVD player"
    }
  ],
  "pollLength": {
    "days": 6,
    "hours": 10
  }
}
%%%

# Duration: 760 ms
# URL: http://localhost:9191/v1/api/polls/244d5bdf-904c-43f1-9781-c5d8b19821ed

# HTTP/1.1 201

@Vary: Origin
@Vary: Access-Control-Request-Method
@Vary: Access-Control-Request-Headers
@Location: http://localhost:9191/v1/api/polls/244d5bdf-904c-43f1-9781-c5d8b19821ed/970b4ac6-0b2d-4ac6-8df1-40553aaf65ce
@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Fri, 13 Dec 2019 18:27:34 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive

{
  "success": true,
  "message": "Poll Created Successfully"
}